require('dotenv').config();
const { testGraphAuthentication, sendGraphEmail } = require('./src/services/microsoftGraph.service');

async function runTests() {
  console.log('--- TESTING MICROSOFT GRAPH AUTHENTICATION ---');
  
  if (!process.env.MICROSOFT_TENANT_ID || !process.env.MICROSOFT_CLIENT_ID || !process.env.MICROSOFT_CLIENT_SECRET) {
    console.error('❌ Missing Microsoft Graph credentials in .env.');
    console.log('Please ensure MICROSOFT_TENANT_ID, MICROSOFT_CLIENT_ID, and MICROSOFT_CLIENT_SECRET are set.');
    return;
  }
  
  const authResult = await testGraphAuthentication();
  console.log(JSON.stringify(authResult, null, 2));
  
  if (!authResult.success) {
    console.error('❌ Authentication failed. Cannot proceed to test email.');
    return;
  }

  console.log('\n--- TESTING MICROSOFT GRAPH EMAIL SENDING ---');
  if (!process.env.MICROSOFT_GRAPH_SENDER_EMAIL) {
    console.error('❌ Missing MICROSOFT_GRAPH_SENDER_EMAIL in .env.');
    return;
  }
  
  // NOTE: Replace this with a valid test recipient before running if needed
  const testRecipient = process.env.TEST_EMAIL_RECIPIENT || 'test@example.com';
  
  try {
    const emailResult = await sendGraphEmail({
      email: testRecipient,
      subject: 'MINDScall Microsoft Graph Integration Test',
      message: 'This is a test email generated by MINDScall using Microsoft Graph API.',
      html: '<p>This is a test email generated by <b>MINDScall</b> using <i>Microsoft Graph API</i>.</p>'
    });
    
    console.log('✅ Email sent successfully!');
    console.log(JSON.stringify(emailResult, null, 2));
  } catch (err) {
    console.error('❌ Failed to send email via Microsoft Graph:');
    console.error(err.message);
  }
}

runTests();
