require('dotenv').config();
const { ClientSecretCredential } = require('@azure/identity');
const { Client } = require('@microsoft/microsoft-graph-client');
require('isomorphic-fetch');

async function testTeamsChat() {
  const tenantId = process.env.MICROSOFT_TENANT_ID;
  const clientId = process.env.MICROSOFT_CLIENT_ID;
  const clientSecret = process.env.MICROSOFT_CLIENT_SECRET;

  const credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
  const client = Client.initWithMiddleware({
    debugLogging: false,
    authProvider: {
      getAccessToken: async () => {
        const tokenResponse = await credential.getToken('https://graph.microsoft.com/.default');
        return tokenResponse.token;
      }
    }
  });

  const testEmail = process.env.TEST_EMAIL_RECIPIENT || 'test@example.com';
  const senderEmail = process.env.MICROSOFT_GRAPH_SENDER_EMAIL;

  console.log('Attempting to create chat with:', { testEmail, senderEmail });

  try {
    const chatPayload = {
      chatType: 'oneOnOne',
      members: [
        {
          '@odata.type': '#microsoft.graph.aadUserConversationMember',
          roles: ['owner'],
          'user@odata.bind': `https://graph.microsoft.com/v1.0/users('${senderEmail}')`
        },
        {
          '@odata.type': '#microsoft.graph.aadUserConversationMember',
          roles: ['owner'],
          'user@odata.bind': `https://graph.microsoft.com/v1.0/users('${testEmail}')`
        }
      ]
    };

    const chatResponse = await client.api('/chats').post(chatPayload);
    console.log('Chat creation successful:', chatResponse.id);

    const messagePayload = {
      body: {
        contentType: 'html',
        content: '<p>MINDScall Teams integration test.</p><p>This message was generated by MINDScall.</p>'
      }
    };

    const messageResponse = await client.api(`/chats/${chatResponse.id}/messages`).post(messagePayload);
    console.log('Message sent successfully:', messageResponse.id);

  } catch (err) {
    console.error('Teams Graph API Failed:');
    console.error(err.message);
    if (err.body) console.error(JSON.stringify(err.body, null, 2));
  }
}

testTeamsChat();
